[package]
name = "hatch"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]

[dependencies]
nix = "0.10.0"
failure = "0.1.1"
tokio-core = "0.1"
tokio-io = "0.1"
futures = "0.1.21"
bytes = "0.4"
trust-dns-resolver = "^0.8"
log = "0.4"
env_logger = "0.5.8"
